version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: hal
      POSTGRES_PASSWORD: haldev
      POSTGRES_DB: hal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 